# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9341f621572cefc10e71328cb987c9e7ed93da8447689eda522db939962bc46470faf40a8a3a60dd7ec34d269b5bfa8017fd85997ea2de1c07fe3df13a6d4fb1

test:
  secret_key_base: 3fa7015bc98cceda4ce0f039f5e905195deb2d6c37a530e462c204a3775af08973c173ab1bc21ece03a23670211b701be78c49db8cf2223a944290afd5abe2a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
